services:
  database:
    image: postgres:13-alpine
    ports:
      - "4444:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mediaoceandb
    volumes:
      - databasedb_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5

  backend:
    build:
      context: ./backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/code
    restart: always
    depends_on:
      - database
    command: >
      sh -c "
        echo 'Running Database Migration'
        alembic upgrade head &&
        sleep 2
        echo 'Starting Gunicorn…' &&
        exec gunicorn manage:app -b 0.0.0.0:5000 --workers 4
      "

  frontend:
    build:
      context: ./frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080

volumes:
  databasedb_data:
