"""removed anomalies and cleaned models


Revision ID: 1c70cc3d28e1
Revises: bb4c59c2baba
Create Date: 2025-07-23 14:36:20.396091

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1c70cc3d28e1"
down_revision = "bb4c59c2baba"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_anomaly_post_id", table_name="anomaly")
    op.drop_index("ix_anomaly_user_id", table_name="anomaly")
    op.drop_table("anomaly")
    op.drop_column("user", "pin_number")
    op.drop_column("user", "image")
    op.drop_column("user", "password_hash")
    op.drop_column("user", "emailVerified")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "emailVerified", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "password_hash", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "user", sa.Column("image", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "user",
        sa.Column(
            "pin_number", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
    )
    op.create_table(
        "anomaly",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_updated",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(length=500), autoincrement=False, nullable=False),
        sa.Column(
            "anomaly_type", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "reason", sa.VARCHAR(length=500), autoincrement=False, nullable=False
        ),
        sa.Column(
            "detected_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.ForeignKeyConstraint(["post_id"], ["post.id"], name="anomaly_post_id_fkey"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], name="anomaly_user_id_fkey"),
        sa.PrimaryKeyConstraint("id", name="anomaly_pkey"),
    )
    op.create_index("ix_anomaly_user_id", "anomaly", ["user_id"], unique=False)
    op.create_index("ix_anomaly_post_id", "anomaly", ["post_id"], unique=False)
    # ### end Alembic commands ###
